uncommented testing workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,37 +32,37 @@ jobs:
         with:
           path: ~/.gradle/caches
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
-          # key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys: ${{ runner.os }}-gradle
       - name: Build and analyze
 
-#      - name: Run unit tests
-#        run: ./gradlew :app:testDebugUnitTest
+      - name: Run unit tests
+        run: ./gradlew :app:testDebugUnitTest
 
-#      - name: Run instrumented tests
-#        id: instrumented_tests
-#        continue-on-error: true
-#        uses: reactivecircus/android-emulator-runner@v2
-#        with:
-#          api-level: 34
-#          arch: x86_64
-#          profile: pixel_6
-#          script: ./gradlew :app:connectedDebugAndroidTest
-#
-#      - name: Generate JaCoCo report
-#        if: always()
-#        run: ./gradlew :app:jacocoTestReport
-#
-#      - name: SonarQube analysis
-#        if: always()
+      - name: Run instrumented tests
+        id: instrumented_tests
+        continue-on-error: true
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: 34
+          arch: x86_64
+          profile: pixel_6
+          script: ./gradlew :app:connectedDebugAndroidTest
+
+      - name: Generate JaCoCo report
+        if: always()
+        run: ./gradlew :app:jacocoTestReport
+
+      - name: SonarQube analysis
+        if: always()
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: ./gradlew build sonar --info
         #run: ./gradlew sonar --info
 
-#      - name: Fail job if instrumented tests failed
-#        if: ${{ always() && steps.instrumented_tests.outcome == 'failure' }}
-#        run: |
-#          echo "Instrumented tests failed. Coverage and SonarQube analysis were still generated."
-#          exit 1
+      - name: Fail job if instrumented tests failed
+        if: ${{ always() && steps.instrumented_tests.outcome == 'failure' }}
+        run: |
+          echo "Instrumented tests failed. Coverage and SonarQube analysis were still generated."
+          exit 1
